config/routes.rb
Rails.application.routes.draw do

  root 'home#show'

  resource :home, :controller => :home
  
  resource :faq, :controller => :faq

  resource :marketplace, :controller => :marketplace do
    resource :admin, :controller => :admin do
      resources :snacks
      resources :price_lists
    end
  end

  get 'download/win' => 'home#download_win'

  get 'download/osx' => 'home#download_osx'

  get 'download/cnf' => 'home#download_cnf'

end

app/models/price_list.rb
class PriceList < ActiveRecord::Base
  has_many :snack_quotes, :dependent => :destroy
  accepts_nested_attributes_for :snack_quotes,  :allow_destroy => true
  has_many :snacks, :through => :snack_quotes

  scope :latest, -> { order('creationtime').last }
  scope :all_reverse_chronological, -> { order('creationtime').reverse_order }

  def self.new_from_template(template_price_list)
    # Initialize the current price list
    price_list = PriceList.new(creationtime: Time.now)

    # Append on unfilled prices if template quote exits
    if !(template_price_list.blank?)
      previousSnacks = []
      for sq in template_price_list.snack_quotes
        price_list.snack_quotes.build(price: sq.price, snack: sq.snack)
        previousSnacks << sq.snack
      end
      for snack in Snack.all.order(:name)
        if !(previousSnacks.include? snack)
          sq = snack.snack_quotes.new
          price_list.snack_quotes << sq
        end
      end
    # Otherwise build an entirely new list
    else
      for snack in Snack.all.order(:name)
        sq = snack.snack_quotes.new
        price_list.snack_quotes << sq
      end
    end
    price_list
  end

  def self.new_from_raw_params(price_list_params)
    
    # Filter out discluded snack quotes, and create deposit addresses for those that remain
    final_snack_quotes_attributes = {}
    co2in_client = Bitcoin::Client.new(Settings.rpcuser, Settings.rpcpassword, :host => Settings.rpchost, :port => Settings.rpcport)
    price_list_params[:snack_quotes_attributes].each do |key, sq|
      if sq['include'] == "1"
        final_snack_quotes_attributes[key] = { 
          'snack_id' => sq['snack_id'], 
          'price' => sq['price'], 
          'deposit_address' => co2in_client.new_address(sq['snack_id'].to_s)
        }
      end
    end
    final_price_list_params = { "snack_quotes_attributes" => final_snack_quotes_attributes }

    price_list = PriceList.new(final_price_list_params)
    price_list.creationtime = Time.now
    price_list
  end
end

app/models/snack.rb
class Snack < ActiveRecord::Base
  has_many :snack_quotes
  has_many :price_lists, :through => :snack_quotes
  validates :name, presence: true, length: { minimum: 5 }
  
  scope :alphabetical_with_balance, -> {
      snacks = includes(:snack_quotes, :price_lists).order(:name)

      # Tack on balances and associated statistics
      co2in_client = Bitcoin::Client.new(Settings.rpcuser, Settings.rpcpassword, :host => Settings.rpchost, :port => Settings.rpcport)
      snacks.each do |snack|
        snack.total_deposit_balance = 0.0
        snack.total_quantity_purchased = 0.0
        snack.firstlisttime = nil
        snack.lastlisttime = nil
        snack.snack_quotes.each do |sq|
          address_balance = co2in_client.getreceivedbyaddress(sq.deposit_address)
          snack.total_deposit_balance += address_balance
          snack.total_quantity_purchased += (address_balance / sq.price)
          if snack.firstlisttime.nil? || sq.price_list.creationtime < snack.firstlisttime
            snack.firstlisttime = sq.price_list.creationtime
          end
          if snack.lastlisttime.nil? || sq.price_list.creationtime > snack.lastlisttime
            snack.lastlisttime = sq.price_list.creationtime
          end
        end
        if snack.total_quantity_purchased > 0
          snack.average_price = snack.total_deposit_balance / snack.total_quantity_purchased
        end
      end

      snacks
  }

  attr_accessor :total_deposit_balance, :total_quantity_purchased, :firstlisttime, :lastlisttime, :average_price
end

app/models/snack_quote.rb
class SnackQuote < ActiveRecord::Base
  belongs_to :snack
  belongs_to :price_list

  scope :alphabetical, -> { includes(:snack).order('snacks.name') }

  scope :alphabetical_with_balance, -> {
    sqs = alphabetical
    
    # Tack on the balances
  co2in_client = Bitcoin::Client.new(Settings.rpcuser, Settings.rpcpassword, :host => Settings.rpchost, :port => Settings.rpcport)
  co2in_balances = co2in_client.listreceivedbyaddress()
  sqs.each do |sq|
    co2in_balances.each do |cb|
        if cb['address'] == sq.deposit_address
      sq.deposit_balance = cb['amount']
      sq.quantity_purchased = cb['amount'] / sq.price
    end
    end
  end

  sqs
  }

  attr_accessor :deposit_balance, :quantity_purchased

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_filter :authenticate

	protected
		def authenticate
			authenticate_or_request_with_http_basic('Administration') do |username, password|
				username == Settings.admin_username && password == Settings.admin_password
				# password_hash = Digest::MD5.hexdigest(password)
				# username == Settings.admin_username && password == Settings.admin_password_hash
			end
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	# before_filter :authenticate

	# protected
	# 	def authenticate
	# 		authenticate_or_request_with_http_basic('Restricted') do |username, password|
	# 			(username == Settings.access_username && password == Settings.access_password) || 
	# 			(username == Settings.admin_username && password == Settings.admin_password)
	# 			# password_hash = Digest::MD5.hexdigest(password)
	# 			# username == Settings.access_username && password == Settings.access_password_hash
	# 		end
	# 	end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def download_win
		send_file 'public/co2in-0.8.7.1-win32-setup.exe',
			:type=>"application/exe", 
			:x_sendfile=>true
	end

	def download_osx
		send_file 'public/CO2IN-Qt.dmg',
			:type=>"application/dmg", 
			:x_sendfile=>true
	end

	def download_cnf
		send_file 'public/co2in.conf',
			:type=>"application/conf", 
			:x_sendfile=>true
	end
	
	def show
	end
end

app/controllers/marketplace_controller.rb
class MarketplaceController < ApplicationController
	def show
		@marketplace = PriceList.latest
	end
end

app/controllers/price_lists_controller.rb
class PriceListsController < AdminController
	def create
		@price_list = PriceList.new_from_raw_params(price_list_params)
		
		if @price_list.save
			redirect_to marketplace_admin_price_list_url(@price_list)
		else 
			render 'new'
		end
	end

	def destroy
		@price_list = PriceList.find(params[:id])
		@price_list.destroy

		redirect_to marketplace_admin_price_lists_path
	end

	def edit
		@price_list = PriceList.find(params[:id])
	end

	def index
		@price_lists = PriceList.all_reverse_chronological
	end

	def new
		@price_list = PriceList.new_from_template(PriceList.latest)		
	end

	def show
		@price_list = PriceList.find(params[:id])
	end

	def update
		@price_list = PriceList.find(params[:id])

		if @price_list.update(snack_params)
			redirect_to marketplace_admin_price_list_url(@price_list)
		else
			render 'edit'
		end
	end

	private
		def price_list_params
			params.require(:price_list).permit(:creationtime, snack_quotes_attributes: [:id, :include, :price, :deposit_address, :snack_id])
		end
end

app/controllers/snacks_controller.rb
class SnacksController < AdminController
	def create
		@snack = Snack.new(snack_params)

		if @snack.save
			redirect_to marketplace_admin_snacks_path
		else 
			render 'new'
		end
	end

	def destroy
		@snack = Snack.find(params[:id])
		@snack.destroy

		redirect_to marketplace_admin_snacks_path
	end

	def edit
		@snack = Snack.find(params[:id])
	end

	def index
		@snacks = Snack.alphabetical_with_balance
	end

	def new
		@snack = Snack.new
	end

	def show
		@snack = Snack.find(params[:id])
	end

	def update
		@snack = Snack.find(params[:id])

		if @snack.update(snack_params)
			redirect_to marketplace_admin_snacks_path
		else
			render 'edit'
		end
	end

	private
		def snack_params
			params.require(:snack).permit(:name, :description)
		end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/marketplace_helper.rb
module MarketplaceHelper
end

app/helpers/price_lists_helper.rb
module PriceListsHelper
end

app/helpers/snacks_helper.rb
module SnacksHelper
end

app/views/admin/show.html.erb
<div class="container container-top">
  <table class="table table-bordered table-hover"> 
    <thead>
      <th>Action Name</th>
      <th>Description</th>
    </thead>
    <tbody>
      <tr>
        <td> <%= link_to 'Manage Price Lists', marketplace_admin_price_lists_path, class: "btn" %> </td>
        <td> Update the current price list and view historical ones </td>
      <tr>
        <td> <%= link_to 'Manage Snacks', marketplace_admin_snacks_path, class: "btn" %> </td>
        <td> Manage the inventory of snacks </td>
      </tr>
    </tbody>
  </table>
  <%= link_to 'Back to Marketplace', marketplace_path, class: "btn" %>
</div>

app/views/faq/show.html.erb
<div class="faq-header"> 
</div>

<div class="container">
  
  <!-- START General Questions Section -->
  <h1 id="general" class="page-header">General</h1>

  <p class="faq-question"> CO2IN? How do I say that? <p>
  <p class="faq-answer"> CO<sub>2</sub> Coin = see-oh-too-coin. </p>

  <p class="faq-question"> Yet another cryptocurrency? Why should I care about CO<sub>2</sub>IN? </p>
  <p class="faq-answer"> After the BETA stage, 20&#37; of all CO<sub>2</sub>IN in existence will be set aside solely for the purchase of <a href="http://en.wikipedia.org/wiki/Carbon_offset">carbon offsets</a>. As more people participate in the CO<sub>2</sub>IN ecosystem and the coin's value grows so too will the value of emissions offsets that can be purchased. </p> 

  <p class="faq-question"> What does it mean for CO<sub>2</sub>IN in beta testing? </p>
  <p class="faq-answer" id="getting-started"> This means that CO<sub>2</sub>IN is only being released to a limited set of people, that the kinks are still being worked out, and that CO<sub>2</sub>IN account balances may be reset to zero upon completion of the BETA. Use at your own risk.</p>

  <p class="faq-question"> OK, I'm sold - I want to help reduce emissions. Or I want to play around with a new cryptocurrency. How the heck do I get started with this thing? </p>
  <div class="faq-answer">
    <p> Start by downloading the official CO<sub>2</sub>IN client. Builds exist for <%= link_to 'Windows', download_win_url %> and <%= link_to 'OS X', download_osx_url %>. Afterwards, you will need to place the following <%= link_to 'configuration file', download_cnf_url %> in one of the following places: </p>
    <ul>
      <li> Windows: C:\Users\[username]\AppData\Roaming\CO2IN, substituting [username] for your username. </li>
      <li> Mac OS X: /Users/[username]/Library/Application Support/CO2IN/, substituting [username] for your username. </li>
    </ul>
    <p> This file will ensure that you connect to valid nodes in the CO<sub>2</sub>IN network and activate mining (see next question) by default. To turn off default mining, just put a "#' character in front of the line that says "gen=1" in the configuration file. </p>
  </div>

  <p class="faq-question"> How do I obtain CO<sub>2</sub>IN? </p>
  <div class="faq-answer"> 
    <p> A computationally-intensive process called mining, which makes CO<sub>2</sub>IN's record of transactions difficult to forge, is rewarded through CO<sub>2</sub>IN. The current reward size is 50 CO2C. To get started with mining simply follow the instructions in the above question. After doing this, you should periodically receive mining rewards when your CO<sub>2</sub>IN is running.</p>
    <p> If you don't want to mine, or are simply eager to get started, simply send an e-mail to the creator with your CO<sub>2</sub>IN address, and he'll send you some (If you're reading this, you probably know who the Creator is). </p>
  </div>
  <!-- END General Questions Section -->

  <!-- START Marketplace Section -->
  <h1 id="implementation" class="page-header">Marketplace</h1>

  <p class="faq-question"> What is the Marketplace? </p>
  <p class="faq-answer"> The Marketplace is an economic experiment targeted at the members of the Aiden Lab based out of the Baylor College of Medicine. Starting on Monday, June 9th, 2014, all snacks provided by the lab will be priced according to the <%= link_to 'Marketplace', marketplace_path %> posted on this website. In order to consume a snack, lab members will need to transfer the listed amount of CO<sub>2</sub>IN to its corresponding deposit address.  </p>

  <p class="faq-question"> That's kind of perverse. What's the point? </p>
  <p class="faq-answer"> We're interesting in collecting on-the-ground data on how money (CO<sub>2</sub>IN) with a clear source of value (snacks) is used by a community of people. Start mining! Or contact the creator with your address to be sent some starter coin. </p>

  <p class="faq-question"> Do prices change? If so, how often? According to what logic? </p>
  <p class="faq-answer"> Yes. We are targeting daily price list changes. The marketplace operators receive 20&#37; of revenues generated on snack sales, so they are incentivized to price snacks in such a way that moves inventory quickly. In short, the prices of in demand snacks should trend higher than those of less popular snacks. </p>

  <p class="faq-question"> Can I use the same deposit address over and over again for given snack? </p>
  <p class="faq-answer"> No. Each time a snack's price changes, the snack's deposit address changes as well. This is for clear accounting of what price (and when) a given snack was purchased. </p>

  <!-- END Marketplace Section -->
  
  <!-- START Implementation Questions Section -->
  <h1 id="implementation" class="page-header">Technology & Implementation</h1>

  <p class="faq-question"> What are the exact specifications for CO<sub>2</sub>IN? </p>
  <div class="faq-answer"> CO2IN is a Litecoin branch with the following parameters:
    <ul>
    <li> Addition of DigiSign difficulty re-adjustment </li>
    <li> Pre-mine of 20% of total currency to here </li>
    <li> 2.5 minute difficulty re-target (every block) </li>
    <li> 50 CO2C initial reward with half life of 840,000 blocks </li>
    <li> 2.5 minute target mine time </li>
    <li> Address prefix is "C" (instead of "L") </li>
    </ul>
  </div>
  
  <p class="faq-question"> You say it's a Litecoin branch, but what's the real the lineage of the CO<sub>2</sub>IN codebase? </p>
  <p class="faq-answer"> CO<sub>2</sub>IN really is a branch of Litecoin! The most significant changes are a hard-coded pre-mine to certain addresses (see the FAQ section on carbon offset purchase) and the DigiSign difficulty re-adjustment algorithm spliced-in. We will periodically merge the latest updates to Litecoin as development resources allow.</p>
  
  <!-- END Implementation Questions Section -->

</div>

app/views/home/show.html.erb
<!-- Header -->


<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="home-header">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h1> CO<sub>2</sub>IN </h1>
        <h3> An new cryptocurrency that directly supports the reduction of CO<sub>2</sub> and other environmentally harmful emissions. </h3>
        <p>&nbsp</p>
        <h4> START USING CO<sub>2</sub>IN: </h4> 
        <p>
          <%= link_to '<span class="fa fa-windows"></span> Windows '.html_safe, {:action => "show", :controller => "faq", :anchor => "getting-started" }, class: "btn btn-primary btn-lg", role: "button" %>
          <%= link_to '<span class="fa fa-apple"></span> OS X '.html_safe, {:action => "show", :controller => "faq", :anchor => "getting-started" }, class: "btn btn-primary btn-lg", role: "button" %>
          <a href="#" class="btn btn-primary btn-lg" role="button" disabled="disabled"><span class="fa fa-linux"></span> Linux </a>
        </p>
        <!-- <p><%= link_to "Detailed Installation Instructions" , {:action => "show", :controller => "faq", :anchor => "getting-started" }, style: "color: #FFFFFF" %></p> -->
        <p>&nbsp</p>
        <h4> BUY CO<sub>2</sub>IN:  </h4> 
        <p><a href="#" class="btn btn-primary btn-lg" role="button" disabled="disabled">Coming Soon</a></p>
      </div>
      <div class="col-md-1">
      </div>
      <div class="col-md-5">
        <!-- The source for the current image came from here - http://commons.wikimedia.org/wiki/File:Carbon_dioxide_3D_ball.png -->
        <%= image_tag "CO2IN.png", class: "img-responsive symbol-big" %>
      </div>
    </div>
  </div>
</div>

<!-- Copy for the coin -->
<div class="container" id="features">
  <div class="row">
    <div class="col-md-4">
      <h3>Reduce Emissions</h3>
      <p>CO<sub>2</sub>IN is the only altcoin that sets aside pre-mined funds (20%) exclusively for purchase of carbon offsets. Funds will be transferred to reputable carbon offset vendors over the course of ~1 year once the coin exits the BETA stage. </p>
    </div>
    <div class="col-md-4">
      <h3>Mine with Confidence</h3>
      <p>CO<sub>2</sub>IN employs Scrypt-based proof-of-work mining combined with a block time of 2 minutes, difficulty re-target of 10 minutes + <a href="http://www.reddit.com/r/Digibyte/comments/1zjeso/eli5_what_is_digishield/"> DigiShield </a>, and reward half-life of 5 years. Enjoy continuing rewards, and protection from large surges and depletions in mining power. </p>
    </div>
    <div class="col-md-4">
      <h3>Support Research</h3>
      <p>CO<sub>2</sub>IN is the output of researchers at Rice Universty's Cultural Observatory and Baylor College of Medicine's Center for Genome Architecture. Participation in the CO<sub>2</sub>IN environment will support ongoing research on the adoption, spending characteristics, and mining of nascent digital currencies. </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CO2IN</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= image_tag "CO2IN.png", class: "navbar-brand img-responsive symbol-navbar" %>
      <%= link_to 'CO<sub>2</sub>IN Beta'.html_safe, home_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if params[:controller] == 'home' %>"><%= link_to 'Home', home_path %></li>
        <li class="<%= 'active' if params[:controller] == 'faq' %>"><%= link_to 'FAQ', faq_path %></li>
        <li class="<%= 'active' if params[:controller] != 'home' and params[:controller] != 'faq' %>"><%= link_to 'Marketplace', marketplace_path %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<div class="animated-content main-body">
  <%= yield %>
</div>

</body>
</html>

app/views/marketplace/show.html.erb
<div class="container container-top">
  <% if !(@marketplace.blank?) %>
  <h4><i>Last Updated on <%= @marketplace.creationtime.to_formatted_s %></i></h4>
  <table class="table table-bordered table-hover"> 
    <thead>
      <th>Snack Name</th>
      <th>Price</th>
      <th>Deposit Address</th>
    </thead>
    <tbody>
      <% @marketplace.snack_quotes.alphabetical.each do |sq| %>
      <tr>
        <td><%= sq.snack.name %></td>
        <td><%= sq.price %> CO2C</td>
        <td><%= sq.deposit_address %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>
  <h4><i>No Prices Currently Listed</i></h4>
  <% end %>
  <%= link_to 'Admin', marketplace_admin_path, class: "btn" %>
</div>

app/views/price_lists/index.html.erb
<div class="container container-top">
  <table class="table table-bordered table-hover"> 
    <thead>
      <th>Time Created</th>
      <th># of Items</th>
      <th>Basket Price</th>
      <th colspan="1"></th>
    </thead>
    <tbody>
      <% @price_lists.each do |price_list| %>
      <tr>
        <td><%= price_list.creationtime.to_formatted_s %></td>
        <td><%= price_list.snack_quotes.length %></td>
        <td>TBD</td>
        <td><%= link_to 'Show', marketplace_admin_price_list_path(price_list) %> |
        <%= link_to 'Delete', marketplace_admin_price_list_path(price_list), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Add Price List', new_marketplace_admin_price_list_path, class: "btn" %> | <%= link_to 'Back to Admin', marketplace_admin_path, class: "btn" %>
</div>

app/views/price_lists/new.html.erb
<div class="container container-top">
  <%= form_for @price_list, url: marketplace_admin_price_lists_path do |f| %>
    <% if @price_list.errors.any? %>
    <div id="error-explanation">
      <h2> Could not save due to errors. Please review your entries. </h2>
    </div>
    <% end %>

    <table class="table table-bordered table-hover"> 
      <thead>
        <th>Include?</th>
        <th>Snack Name</th>
        <th>Last Price</th>
        <th>New Price</th>
      </thead>
      <tbody>
        <%= f.fields_for :snack_quotes do |g| %>
          <tr>
            <td><%= g.check_box :include, :checked => (g.object.price ? true : false) %></td>
            <td><%= g.object.snack.name %> <%= g.hidden_field :snack_id %> </td>
            <td><%= g.object.price || "&mdash;".html_safe %> CO2C</td>
            <td><%= g.text_field :price %> CO2C</td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= f.submit :class => "btn btn-primary" %>
  <% end %>
  <%= link_to 'Back', marketplace_admin_price_lists_path, class: "btn" %>
</div>

app/views/price_lists/show.html.erb
<div class="container container-top">
  <table class="table table-bordered table-hover"> 
    <thead>
      <th>Snack Name</th>
      <th>Price</th>
      <th>Deposit Address</th>
      <th>Quantity Purchased</th>
    </thead>
    <tbody>
      <% @price_list.snack_quotes.alphabetical_with_balance.each do |sq| %>
      <tr>
        <td><%= sq.snack.name %></td>
        <td><%= sq.price %> CO2C</td>
        <td><%= sq.deposit_address %></td>
        <td><%= sq.quantity_purchased || "&mdash;".html_safe%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Back to Price Lists', marketplace_admin_price_lists_path, class: "btn" %> | <%= link_to 'Edit', edit_marketplace_admin_price_list_path(@price_list), class: "btn" %>
</div>

app/views/snacks/edit.html.erb
<div class="container container-top">
  <%= form_for :snack, url: marketplace_admin_snack_path(@snack), method: :patch do |f| %>
    <% if @snack.errors.any? %>
    <div id="error-explanation">
      <h2><%= pluralize(@snack.errors.count, "error") %> prohibited this snack from being saved:</h2>
      <ul>
      <% @snack.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <%end%>
      </ul>
      <br>
    </div>
    <% end %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </p>

    <p>
      <%= f.submit :class => "btn btn-primary" %>
    </p>
  <% end %>
  <%= link_to 'Back', marketplace_admin_snacks_path, class: "btn" %>
</div>

app/views/snacks/index.html.erb
<div class="container container-top">
  <table class="table table-bordered table-hover"> 
    <thead>
      <th>Name</th>
      <th>Description</th>
      <th>Quantity Purchased</th>
      <th>Average Sale Price</th>
      <th>First List Time</th>
      <th>Last List Time</th>
      <th colspan="1"></th>
    </thead>
    <tbody>
      <% @snacks.each do |snack| %>
      <tr>
        <td><%= snack.name%></td>
        <td><%= snack.description%></td>
        <td><%= snack.total_quantity_purchased || "&mdash;".html_safe%></td>
        <td><%= snack.average_price || "&mdash;".html_safe%> CO2C</td>
        <td><%= snack.firstlisttime || "&mdash;".html_safe%></td>
        <td><%= snack.lastlisttime || "&mdash;".html_safe%></td>
        <td><%= link_to 'Edit', edit_marketplace_admin_snack_path(snack) %> | <%= link_to 'Delete', marketplace_admin_snack_path(snack), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Add Snack', new_marketplace_admin_snack_path, class: "btn" %> | <%= link_to 'Back to Admin', marketplace_admin_path, class: "btn" %>
</div>

app/views/snacks/new.html.erb
<div class="container container-top">
  <%= form_for :snack, url: marketplace_admin_snacks_path do |f| %>
    <% if @snack.errors.any? %>
    <div id="error-explanation">
      <h2><%= pluralize(@snack.errors.count, "error") %> prohibited this snack from being saved:</h2>
      <ul>
      <% @snack.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <%end%>
      </ul>
      <br>
    </div>
    <% end %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </p>

    <p>
      <%= f.submit :class => "btn btn-primary" %>
    </p>
  <% end %>
  <%= link_to 'Back', marketplace_admin_snacks_path, class: "btn" %>
</div>

app/views/snacks/show.html.erb
<div class="container container-top">
  <p>
    <strong>Name:</strong>
    <%= @snack.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @snack.description %>
  </p>

  <%= link_to 'Back to Snacks', marketplace_admin_snacks_path, class: "btn" %> | <%= link_to 'Edit', edit_marketplace_admin_snack_path(@snack), class: "btn" %>
</div>